package Principal;

/**
 * clase que contiene todos los tokens definidos y utilizados
 */
public enum Token {
     ERROR, DEFINICION, CONJUNTO_UNIVERSO, LLAVE_ABIERTA, LLAVE_CERRADA,
     COMA, IGUAL, ELEMENTO, SPACES, NUEVA_LINEA, CONJUNTO, OPERACION, PARENTESIS_ABIERTO,
     PARENTESIS_CERRADO, UNION, INTERSECCION, DIFERENCIA, PRODUCTO_CRUZ,
     COMPLEMENTO, OPERACION_CONJUNTO, LETRA_MAYUSCULA,
     COMILLA, CONJUNTO_VACIO,SPACE, UNIVERSO, COMILLAS, ELEMENTO_GLOBAL, ELEMENTO_CONJUNTO,
     NOMBRE_CONJUNTO,
}
